version: '3'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test123'
      MYSQL_DATABASE: 'testDB'

  fbb-back:
    build: ./server/.
    ports:
      - "8088:8088"
    depends_on:
      - db

  fbb-front:
    build: ./web/.
    volumes: 
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      -  "8080:8080"
    depends_on:
      - fbb-back
    command: [nginx-debug, '-g', 'daemon off;'] # debug 模式
    # command: ["nginx", "-g", "daemon off;"]