version: '3'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: '123456'

  fbb:
    build: .
    # command: [/bin/bash]  #["/bin/bash", "/fisco-bcos-browser/deploy_browser.sh"]
    # volumes:
    #   - ~/*/build:/bcos-data
    ports:
      - "8080:8080"
    depends_on:
      - db